name: Build
on:
  push:
    branches:
      - frontend

jobs:
  #SONARCLOUD
  sonarcloud:
    name: DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Cambia esto a tu versi√≥n de Node.js

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: ng build --prod

      #DOCKER HUB
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/solcoin:latest .
  
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/solcoin:latest
